---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-ingress
  labels:
    app: nginx-ingress
    release: prom
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      scrapeTimeout: 30s
      port: metrics
      path: /metrics
  namespaceSelector:
    matchNames:
      - nginx-ingress
  selector:
    matchLabels:
      app: nginx-ingress
      component: controller

