---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    app: node-exporter
    release: prom
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      scrapeTimeout: 30s
      port: metrics
      path: /metrics
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_app, __meta_kubernetes_pod_node_name]
          action: replace
          regex: node-exporter;(.+)
          replacement: $1
          targetLabel: instance
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app: node-exporter

