apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "symfony-demo.fullname" . }}
  labels:
{{ include "symfony-demo.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "symfony-demo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        config-checksom/nginx-config: {{ include (print $.Template.BasePath "/nginx-config.yaml") . | sha256sum }}
        config-checksom/symfony-env: {{ include (print $.Template.BasePath "/symfony-env.yaml") . | sha256sum }}
        linkerd.io/inject: enabled
      labels:
        app.kubernetes.io/name: {{ include "symfony-demo.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: fpm
          image: "{{ .Values.image.repositoryFpm }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/www/html/.env
              subPath: .env
              name: symfony-env
          ports:
            - name: fastcgi
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: fastcgi
          readinessProbe:
            tcpSocket:
              port: fastcgi
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: nginx
          image: "{{ .Values.image.repositoryNginx }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "symfony-demo.fullname" . }}-nginx
        - name: symfony-env
          configMap:
            name: {{ include "symfony-demo.fullname" . }}-symfony-env
