image:
  tag: 1.0.0

replicaCount: 1

ingress:
  enabled: true
  hosts:
    - host: symfony-demo.<YOURNAME>.metakube.org
      paths:
        - /

  tls:
    - hosts:
      - symfony-demo.<YOURNAME>.metakube.org
