kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: web-application
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    app: web-application
    workshop: workshop
spec:
  tls:
    - hosts:
        - web-application.<YOUR_NAME>.metakube.org
      # secretName: web-application-tls
  rules:
    - host: web-application.<YOUR_NAME>.metakube.org
      http:
        paths:
          - path: /
            backend:
              serviceName: web-application
              servicePort: 80
