apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: simon-dev
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: simon-dev
subjects:
- kind: ServiceAccount
  name: simon-dev
  namespace: dev
