apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # root password is required to be specified
  # lNohecTcJZJD9zN5WLHC8lJYjymtHBeMSQkUyMpn
  ROOT_PASSWORD: bE5vaGVjVGNKWkpEOXpONVdMSEM4bEpZanltdEhCZU1TUWtVeU1wbg==
  # application credentials that will be created at cluster bootstrap
  # syseleven
  DATABASE: c3lzZWxldmVu
  # metakube
  USER: bWV0YWt1YmU=
  # lNohecTcJZJD9kmsldnsvsdaseE
  PASSWORD: bE5vaGVjVGNKWkpEOWttc2xkbnN2c2Rhc2VF
