apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "quote-svc.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "quote-svc.name" . }}
    helm.sh/chart: {{ include "quote-svc.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    prometheus: k8s
    release: prom
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      scrapeTimeout: 30s
      port: http
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "quote-svc.name" . }}
